version: 2
jobs:
  build:
    working_directory: ~/crank
    docker:
      - image: crystallang/crystal:0.34.0
    steps:
      - checkout
      - run:
          name: test
          command: crystal spec
